import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import LayoutTransition from "@/components/LayoutTransition";
import StairTransition from "@/components/StairTransition";
import Footer from "@/components/Footer";

const jetbrainMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetbrain-mono",
});

export const metadata = {
  title: "Fahmudul Hassan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      

      <body className={jetbrainMono.variable}>
        <Header />
        <StairTransition />
        <LayoutTransition>{children}</LayoutTransition>
        <Footer />
      </body>
    </html>
  );
}
